export const rolePermissions = {
  SuperAdmin: [
    'instituciones.ver',
    'configuracion.institucional.editar',
    'usuarios.crear',
    'usuarios.editar',
    'usuarios.eliminar',
    'reportes.globales.ver',
    'reportes.individuales.ver',
    'cursos.ver',
    'cursos.crear',
    'cursos.editar',
    'cursos.eliminar',
    'modulos.ver',
    'modulos.crear',
    'modulos.editar',
    'modulos.eliminar',
    'contenidos.ver',
    'contenidos.crear',
    'contenidos.editar',
    'contenidos.eliminar',
    'calificaciones.ver',
    'calificaciones.editar',
  ],
  Admin: [
    'usuarios.crear',
    'usuarios.ver',
    'usuarios.editar',
    'usuarios.eliminar',
    'cursos.crear',
    'cursos.editar',
    'cursos.eliminar',
    'cursos.ver',
    'modulos.crear',
    'modulos.editar',
    'modulos.eliminar',
    'modulos.ver',
    'contenidos.crear',
    'contenidos.editar',
    'contenidos.eliminar',
    'contenidos.ver',
    'reportes.institucionales.ver',
  ],
  Docente: [
    'cursos.asignados.ver',
    'modulos.crear',
    'modulos.editar',
    'modulos.eliminar.propios',
    'contenidos.crear',
    'contenidos.editar',
    'contenidos.eliminar.propios',
    'evaluaciones.crear',
    'calificaciones.editar',
    'estudiantes.ver',
    'seguimiento.academico',
  ],
  Estudiante: [
    'cursos.inscritos.ver',
    'modulos.desbloqueados.ver',
    'contenidos.consumir',
    'evaluaciones.presentar',
    'tareas.enviar',
    'actividades.participar',
    'progreso.ver',
    'calificaciones.ver.propias',
  ],
};

export const getPermissionsForRoles = (roles = []) => {
  return [...new Set(roles.flatMap((role) => rolePermissions[role] || []))].sort();
};